services:
  eventstore:
    image: eventstore/eventstore:22.10.1-buster-slim
    container_name: eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_DISCOVER_VIA_DNS=false
      - EVENTSTORE_GOSSIP_ON_SINGLE_NODE=true
    volumes:
      - eventstore-data:/var/lib/eventstore
    networks:
      eventstore-network:
        aliases:
          - eventstore
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2113/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  pubsub-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - EventStore__ConnectionString=esdb://admin:changeit@eventstore:2113?tls=false
    depends_on:
      eventstore:
        condition: service_healthy
    networks:
      eventstore-network:
        aliases:
          - pubsub-app

networks:
  eventstore-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  eventstore-data: